"use client";

import { useAdminToast } from "@/app/components/admin/AdminToast";

const REPORTS = [
  {
    title: "Genetics_Module4.pdf",
    subtitle: "Uploaded by Rahul M.",
    reportedBy: "Anjali T.",
    reason: "Copyright concern",
    date: "41m ago",
    severity: "High",
  },
  {
    title: 'Presentation: "Exam Prep Tips"',
    subtitle: "Generated by Vikram N.",
    reportedBy: "Priya S.",
    reason: "Inaccurate content",
    date: "3h ago",
    severity: "Medium",
  },
  {
    title: "Cell_Division_Notes.docx",
    subtitle: "Uploaded by Priya S.",
    reportedBy: "System auto-flag",
    reason: "Large file scan",
    date: "1d ago",
    severity: "Low",
  },
];

const SEVERITY_BADGE: Record<string, string> = {
  High: "bg-[#fff1f1] text-[#dc2626]",
  Medium: "bg-[#fff8e7] text-[#ca8a04]",
  Low: "bg-[#f0f1f5] text-[#9ca3af]",
};

export default function ReportsPage() {
  const toast = useAdminToast();

  return (
    <div className="p-6">
      <div className="mb-1 text-[17px] font-semibold text-[#111827]">Flagged Reports</div>
      <div className="mb-5 text-[12px] text-[#9ca3af]">Content reported by users — review and take action</div>

      <div className="overflow-hidden rounded-xl border border-[#e4e6eb] bg-white">
        <div className="overflow-x-auto">
          <table className="w-full text-[13px]">
            <thead>
              <tr className="border-b border-[#e4e6eb]">
                {["Content", "Reported by", "Reason", "Date", "Severity", "Actions"].map((h) => (
                  <th key={h} className="px-4 py-2.5 text-left text-[11px] font-semibold uppercase tracking-[0.6px] text-[#9ca3af]">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {REPORTS.map((r) => (
                <tr key={r.title} className="border-b border-[#edeef2] last:border-none hover:bg-[#f7f8fa]">
                  <td className="px-4 py-3">
                    <div className="text-[13px] text-[#111827]">{r.title}</div>
                    <div className="text-[11px] text-[#9ca3af]">{r.subtitle}</div>
                  </td>
                  <td className="px-4 py-3 text-[#4b5563]">{r.reportedBy}</td>
                  <td className="px-4 py-3 text-[#4b5563]">{r.reason}</td>
                  <td className="px-4 py-3 text-[#4b5563]">{r.date}</td>
                  <td className="px-4 py-3">
                    <span className={`rounded px-2 py-0.5 text-[10px] font-semibold ${SEVERITY_BADGE[r.severity]}`}>{r.severity}</span>
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => toast("Content reviewed — kept")}
                        className="rounded-lg border border-[#e4e6eb] px-3 py-1.5 text-[12px] font-medium text-[#4b5563] hover:bg-[#f7f8fa]"
                      >
                        Keep
                      </button>
                      <button
                        onClick={() => toast("Content removed")}
                        className="rounded-lg px-3 py-1.5 text-[12px] font-medium"
                        style={{ background: "#fff1f1", color: "#dc2626" }}
                      >
                        Remove
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
